### ISSUE TITLE
Deployment was unable to start. Hypervisor was unable to start instances.

### ISSUE THREAD

**Issue by biozzl** [Misaka-blog/KOXray#10]
Deployment was unable to start. Hypervisor was unable to start instances.
![](https://s3.bmp.ovh/imgs/2022/04/15/4c91cceaa3e557ea.png)

**Comment by Lemonawa** [comment]
@biozzl 这个仓库嘛，已经寄了

**Comment by Lemonawa** [comment]
看 #6
