### ISSUE TITLE
请问这个项目还能用吗？？

### ISSUE THREAD

**Issue by ghft665** [Misaka-blog/KOXray#17]
部署完后显示unhealthy怎么回事？？

**Comment by uloveme** [comment]
> 部署完后显示unhealthy怎么回事？？

可以用的，我还是fork的https://github.com/ShoukakuChuuCC/Koyeb，今天第七天停机也是显示unhealthy,重新部署又可以用了

**Comment by misakano7545** [comment]
> 部署完后显示unhealthy怎么回事？？

可能是koyeb暂时限制了，或者是100g流量用完了
