### ISSUE TITLE
最后一步部署错误

### ISSUE THREAD

**Issue by gd1214b** [Misaka-blog/KOXray#3]
如图

***
![屏幕截图 2022-03-05 150030](https://user-images.githubusercontent.com/37929478/156872547-95bc9310-6c0a-4019-8e8f-4ea11cd1811f.png)
***
![屏幕截图 2022-03-05 145958](https://user-images.githubusercontent.com/37929478/156872549-98dea2f6-7b19-4aa1-a358-d2616ac41709.png)
***
![屏幕截图 2022-03-05 145938](https://user-images.githubusercontent.com/37929478/156872550-6e0e6d71-9427-4b9b-801f-2366261f6607.png)
***
![屏幕截图 2022-03-05 150202](https://user-images.githubusercontent.com/37929478/156872541-09a2b5d2-2529-495e-8fa8-a096368dcb37.png)

**Comment by misakano7545** [comment]
重新部署试试看

**Comment by gd1214b** [comment]
> 重新部署试试看

还是不行

**Comment by misakano7545** [comment]
今天下午测试都没啥问题，要不来TG给我看一下？

**Comment by gd1214b** [comment]
现在不知怎么就恢复正常了，初步怀疑是Koyeb服务器的问题。

**Comment by misakano7545** [comment]
能用就行
