### ISSUE TITLE
大无语事件 【结论：Koyeb目前已经识别了这个项目，请谨慎部署】

### ISSUE THREAD

**Issue by gitiray** [Misaka-blog/KOXray#6]
大无语事件，注册完成所有步骤，刚部署到一半，帐号突然自动退出。
预感不妙，重新登录，提示地址无效，但尝试重新注册又提示邮箱已存在
找回密码也收不到邮件。

被封号了。

**Comment by Lemonawa** [comment]
@gitiray 没办法，再注册一个吧

**Comment by Lemonawa** [comment]
@gitiray 没什么无语的，习惯就好

**Comment by gitiray** [comment]
还没部署完成就强行退出登陆，说明项目已经被识别了，不打算再搞了，也建议各位慎重使用
