### ISSUE TITLE
CADDYIndexPage：伪装站首页文件不太明白意思，能否细说一下，谢谢！

### ISSUE THREAD

**Issue by liuwleo** [Misaka-blog/KOXray#9]

**Comment by misakano7545** [comment]
@liuwleo 顾名思义，就是伪装首页你想自定义的文件

**Comment by liuwleo** [comment]
> @liuwleo 顾名思义，就是伪装首页你想自定义的文件

初级小白。那具体如何设置呢？目前已部署好，测速也可以，但是就是无法连接。整个过程好像就这个环节没做对。所以想请教一下。谢谢

**Comment by misakano7545** [comment]
@liuwleo 没截图 说什么 我看空气啊！
